version: "2.3"
services:
    proposals:
        build: .
        ipc: host
        command: "python3 propose.py 30"
        #volumes:
        #    - .:/develop/
        #command: "tail -F /dev/null"
        environment:
            - DBCONNECT
        networks:
          - cosmosnet

networks:
  cosmosnet:
      name: cosmosnet
