version: "2.3"
services:
    ingestion:
        build: .
        ipc: host
        volumes:
            - ${INPUT_DIR}:/input/
        command: "python3 pdf_ingestion.py /input 30 --skip"
#        command: "tail -f /dev/null"
        environment:
            - DBCONNECT
        networks:
          - cosmosnet

networks:
  cosmosnet:
      name: cosmosnet
