version: "2.3"
services:
    ocr:
        build: .
        ipc: host
        command: "python3 ocr.py 30 --skip"
        volumes:
            - .:/develop/
#        command: "tail -F /dev/null"
        environment:
            - DBCONNECT
        networks:
          - cosmosnet

networks:
  cosmosnet:
      name: cosmosnet
