version: '2.3'
services:
  mongo-test:
    image: mongo
    container_name: mongo-test
    environment:
      - MONGO_INITDB_ROOT_USERNAME=cosmos
      - MONGO_INITDB_ROOT_PASSWORD=password
    volumes:
      - /ssd/iaross/mongodata:/data/db/
    networks:
      - cosmosnet

#
#volumes:
#  mongodata:
#    driver: local

networks:
  cosmosnet:
      name: cosmosnet
