version: "2.3"
services:
    detection:
        build: .
        runtime: nvidia
        ipc: host
        command: 
            - /bin/bash
            - -c
            - |
              export LC_ALL=C.UTF-8
              export LANG=C.UTF-8
              python3 detect.py model_config.yaml model_weights.pth 30 --skip
        #volumes:
        #    - .:/develop/
        #command: "tail -F /dev/null"
        environment:
            - DBCONNECT
            - DEVICE
        networks:
          - cosmosnet

networks:
  cosmosnet:
      name: cosmosnet
